# Site settings
title: Kokjtu
description: Kokjtu's portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cuong Pham
user_description: Develop web applications
user_title: Full Stack Developer
email: kokjtu@gmail.com
twitter_username: kokjtu
github_username:  kokjtu
gplus_username:  kokjtu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
